# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-24 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=30, verbose_name='登录密码')),
                ('email', models.EmailField(max_length=40, verbose_name='登录邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Basicinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1, verbose_name='性别')),
                ('ageday', models.IntegerField(max_length=2, verbose_name='天')),
                ('ageyear', models.IntegerField(max_length=4, verbose_name='年')),
                ('agemonth', models.IntegerField(max_length=2, verbose_name='月')),
                ('marrystat', models.CharField(max_length=1, verbose_name='婚姻状况')),
                ('education', models.CharField(max_length=1, verbose_name='学历')),
                ('height', models.IntegerField(max_length=3, verbose_name='身高')),
                ('weight', models.IntegerField(max_length=3, verbose_name='体重')),
                ('province', models.CharField(max_length=2, verbose_name='所在地区')),
                ('lovesort', models.CharField(max_length=1, verbose_name='交友类型')),
                ('qq', models.CharField(max_length=15, verbose_name='QQ号码')),
                ('homepage', models.CharField(max_length=30, verbose_name='微博/博客')),
                ('idnumber', models.CharField(max_length=18, verbose_name='身份证号码')),
            ],
        ),
    ]
