# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-15 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=70, verbose_name='登录密码')),
                ('email', models.EmailField(max_length=40, verbose_name='登录邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Basicinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=5, verbose_name='性别')),
                ('ageday', models.IntegerField(verbose_name='天')),
                ('ageyear', models.IntegerField(verbose_name='年')),
                ('agemonth', models.IntegerField(verbose_name='月')),
                ('marrystat', models.CharField(max_length=10, verbose_name='婚姻状况')),
                ('education', models.CharField(max_length=10, verbose_name='学历')),
                ('height', models.IntegerField(verbose_name='身高')),
                ('weight', models.IntegerField(verbose_name='体重')),
                ('province', models.CharField(max_length=10, verbose_name='所在地区')),
                ('lovesort', models.CharField(max_length=10, verbose_name='交友类型')),
                ('qq', models.CharField(blank=True, max_length=15, null=True, verbose_name='QQ号码')),
                ('homepage', models.CharField(blank=True, max_length=30, null=True, verbose_name='微博/博客')),
                ('idnumber', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号码')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Accountinfo')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
