# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190811_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='password',
            field=models.CharField(max_length=70, verbose_name='登录密码'),
        ),
    ]
